# Generated by Django 5.1.5 on 2025-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
