# Generated by Django 5.1.5 on 2025-03-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_alter_task_end_time_alter_task_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='class_id',
        ),
        migrations.AddField(
            model_name='project',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmaps.class'),
        ),
    ]
