# Generated by Django 5.1.5 on 2025-03-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0005_remove_project_class_id_project_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='class_id',
            new_name='class_instance',
        ),
    ]
