# Generated by Django 5.1.5 on 2025-03-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0006_rename_class_id_project_class_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='parent_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='class_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.class'),
        ),
    ]
