# Generated by Django 5.1.5 on 2025-03-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_taskcategory_task_color_taskcategory_task_roadmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='task_color',
            new_name='cat_color',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='name',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='taskcategory',
            old_name='task_roadmap',
            new_name='cat_roadmap',
        ),
    ]
