# Generated by Django 5.1.5 on 2025-03-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0010_remove_roadmap_metadata_roadmap_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(auto_now_add=True, null=True)),
                ('parent_roadmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.roadmap')),
            ],
        ),
    ]
