# Generated by Django 5.1.5 on 2025-03-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0011_roadmapsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapsection',
            name='section_name',
            field=models.CharField(default='Section', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roadmapsection',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='roadmapsection',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
