# Generated by Django 5.1.5 on 2025-03-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0012_roadmapsection_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapsection',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
    ]
