# Generated by Django 5.1.5 on 2025-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0015_roadmapsection_start_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='width_percentage',
            field=models.FloatField(null=True),
        ),
    ]
