# Generated by Django 5.1.5 on 2025-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0016_task_start_percent_task_width_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='cat_rows',
            field=models.IntegerField(null=True),
        ),
    ]
