# Generated by Django 5.1.5 on 2025-04-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0017_taskcategory_cat_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskrow_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskrow_cat', to='roadmaps.taskcategory')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='task_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmaps.taskrow'),
        ),
    ]
