# Generated by Django 5.1.5 on 2025-04-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0018_taskrow_task_task_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrow',
            name='end_time',
            field=models.DateField(null=True),
        ),
    ]
