# Generated by Django 5.1.5 on 2025-04-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0019_taskrow_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_row',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_set', to='roadmaps.taskrow'),
        ),
    ]
