# Generated by Django 5.2 on 2025-04-29 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0021_alter_task_category_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.project')),
                ('students', models.ManyToManyField(related_name='group_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
