# Generated by Django 5.2 on 2025-04-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0022_grouproadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproadmap',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_roadmaps', to='roadmaps.project'),
        ),
    ]
