# Generated by Django 5.2 on 2025-04-29 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0023_alter_grouproadmap_parent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproadmap',
            name='roadmap',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.roadmap'),
        ),
        migrations.AlterField(
            model_name='grouproadmap',
            name='parent_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roadmaps.project'),
            preserve_default=False,
        ),
    ]
