# Generated by Django 5.2 on 2025-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0024_grouproadmap_roadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
